require: rubocop-rspec
require: rubocop-rails

AllCops:
  Exclude:
    - 'config/**/**'
    - 'config.ru'
    - 'Rakefile'
    - 'lib/**/**'
    - 'Gemfile.lock'
    - 'bin/**'
    - 'db/**/**'
    - 'app/helpers/**/**'
    - 'app/assets/**'
    - 'app/mailers/**'
    - 'spec/helpers/**'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
